services:
    api:
        build:
            dockerfile: ./docker/DockerfilePhp
        ports:
            - "8090:80"
        volumes:
            - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
            - ./src:/var/www/html
        depends_on:
            database:
                condition: service_healthy

    database:
        image: mariadb:10.4
        container_name: database
        environment: # Accepted security risk for sake of development speed
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypass
        ports:
            - "3306:3306"
        volumes:
            - ./schema/:/docker-entrypoint-initdb.d:ro
        healthcheck:
           test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pRootpass" ]
           interval: 5s
           timeout: 3s
           retries: 20
